docs/linux/sql-server-linux-whats-new.md

linguistic fixes

---

docs/linux/sql-server-linux-whats-new.md

Pull request opened by OPS to resolve syncing conflicts from FromPrivateLive to live.

Resolve syncing conflicts from FromPrivateLive to live

---

docs/t-sql/statements/alter-database-scoped-configuration-transact-sql.md

Automatic translation changed in many paragraphs

Completely translated (ITA)

---

docs/sql-operations-studio/what-is.md

What is page completely translated. The previous version was automatically translated and wrong in many places.

what is page completely translated

---

docs/sql-operations-studio/TOC.md

Installare --> Installazione
utilizzo dello spazio delle tabelle --> spazio utilizzato dalle tabelle

Some terms changed on TOC.md

---

docs/sql-operations-studio/quickstart-sql-database.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/29

Aldonetti patch 2

---

docs/sql-operations-studio/tutorial-backup-restore-sql-server.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/33

Suxstellino patch 15

---

docs/sql-operations-studio/new-updated-sql-operations-studio.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/60

Suxstellino patch 18

---

docs/sql-operations-studio/download.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/62

Suxstellino patch 19

---

docs/sql-operations-studio/download.md

- Marzo, not Febbraio
- High Sierra, not Sierra Elevata

donwload.md minor fixes

---

docs/sql-operations-studio/server-groups.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/53

Suxstellino patch 6

---

docs/sql-operations-studio/keyboard-shortcuts.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/52

Suxstellino patch 5

---

docs/sql-operations-studio/insight-widgets.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/44

Suxstellino patch 1

---

docs/sql-operations-studio/code-snippets.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/46

Suxstellino patch 3

---

docs/sql-operations-studio/release-notes.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/37

Suxstellino patch 16

---

docs/sql-operations-studio/tutorial-sql-editor.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/28

Suxstellino patch 11

---

docs/sql-operations-studio/enable-kerberos.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/56

Suxstellino patch 14

---

docs/sql-operations-studio/faq.md

https://github.com/MicrosoftDocs/sql-docs.it-it/pull/59

Suxstellino patch 17

---

docs/relational-databases/system-stored-procedures/sp-updatestats-transact-sql.md

sp-updatestats-transact-sql.md major changes

---

docs/relational-databases/system-dynamic-management-views/sys-dm-io-virtual-file-stats-transact-sql.md

Reverts MicrosoftDocs/sql-docs.it-it#86

Revert "Update sys-dm-io-virtual-file-stats-transact-sql.md"
